# .github/workflows/code_checks.yaml
name: Code_Checks

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0']
        stability: [ prefer-lowest, prefer-stable ]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} tests
    steps:
      # basically git clone
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      # use PHP of specific version
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pcov, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: pcov # none, disable xdebug, pcov

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --verbose


  #cs:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- uses: shivammathur/setup-php@v2
        #with:
          #php-version: 8.0
          #coverage: none # disable xdebug, pcov
      #- run: composer install --no-progress
      #- run: composer cscheck


  #phpstan:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- uses: shivammathur/setup-php@v2
        #with:
          #php-version: 8.0
          #coverage: none # disable xdebug, pcov
      #- run: composer install --no-progress
      #- run: composer phpstan
